"""Tests for docker-compose and nginx config generation."""

import yaml
import mclib


# ---------------------------------------------------------------------------
# Compose generation — structure
# ---------------------------------------------------------------------------

class TestComposeStructure:
    def test_has_services_and_networks(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        assert 'services' in compose
        assert 'networks' in compose
        assert 'minecraft-net' in compose['networks']

    def test_has_header_comment(self, sample_manifest):
        raw = mclib.generate_compose(sample_manifest)
        assert raw.startswith('# Generated by mc-generate')

    def test_service_order(self, sample_manifest):
        raw = mclib.generate_compose(sample_manifest)
        acme_pos = raw.index('acme-dns')
        router_pos = raw.index('mc-router')
        creative_pos = raw.index('creative:')
        test_pos = raw.index('test:')
        assert acme_pos < router_pos < creative_pos < test_pos


# ---------------------------------------------------------------------------
# Compose generation — acme-dns (static service)
# ---------------------------------------------------------------------------

class TestComposeAcmeDns:
    def test_acme_dns_present(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        acme = compose['services']['acme-dns']
        assert acme['build'] == './acme-dns'
        assert acme['container_name'] == 'acme-dns'
        assert acme['restart'] == 'unless-stopped'

    def test_acme_dns_ports(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        ports = compose['services']['acme-dns']['ports']
        assert '53:53' in ports
        assert '53:53/udp' in ports
        assert '127.0.0.1:8053:80' in ports

    def test_acme_dns_volumes(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        volumes = compose['services']['acme-dns']['volumes']
        assert './acme-dns/config:/etc/acme-dns:ro' in volumes
        assert './acme-dns/data:/var/lib/acme-dns' in volumes


# ---------------------------------------------------------------------------
# Compose generation — mc-router
# ---------------------------------------------------------------------------

class TestComposeMcRouter:
    def test_router_image(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        router = compose['services']['mc-router']
        assert router['image'] == 'itzg/mc-router'
        assert router['container_name'] == 'mc-router'

    def test_router_mapping(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        mapping = compose['services']['mc-router']['environment']['MAPPING']
        assert 'creative.mc.danny.is=creative:25565' in mapping
        assert 'test.mc.danny.is=test:25565' in mapping

    def test_router_on_minecraft_net(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        assert 'minecraft-net' in compose['services']['mc-router']['networks']


# ---------------------------------------------------------------------------
# Compose generation — MC servers
# ---------------------------------------------------------------------------

class TestComposeMcServer:
    def test_basic_fields(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        creative = compose['services']['creative']
        assert creative['image'] == 'itzg/minecraft-server'
        assert creative['container_name'] == 'creative'
        assert creative['restart'] == 'unless-stopped'
        assert 'minecraft-net' in creative['networks']

    def test_env_file(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        assert compose['services']['creative']['env_file'] == ['servers/creative/env']
        assert compose['services']['test']['env_file'] == ['servers/test/env']

    def test_environment_constants(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        env = compose['services']['creative']['environment']
        assert env['EULA'] == 'TRUE'
        assert env['WHITELIST_ENABLED'] == 'true'
        assert env['ENFORCE_WHITELIST'] == 'true'
        assert env['RCON_PASSWORD'] == '${RCON_PASSWORD:-changeme}'
        assert env['USE_AIKAR_FLAGS'] == 'true'
        assert env['REMOVE_OLD_MODS'] == 'TRUE'

    def test_optimisation_flags_on_all_servers(self, sample_manifest):
        """USE_AIKAR_FLAGS and REMOVE_OLD_MODS should be set on every MC server."""
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        for name in sample_manifest['servers']:
            env = compose['services'][name]['environment']
            assert env['USE_AIKAR_FLAGS'] == 'true', f'{name} missing USE_AIKAR_FLAGS'
            assert env['REMOVE_OLD_MODS'] == 'TRUE', f'{name} missing REMOVE_OLD_MODS'

    def test_environment_from_manifest(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        env = compose['services']['creative']['environment']
        assert env['TYPE'] == 'FABRIC'
        assert env['VERSION'] == 'LATEST'
        assert env['MEMORY'] == '4G'
        assert env['MODE'] == 'creative'
        assert env['MOTD'] == 'Creative Server'

    def test_modrinth_projects(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        projects = compose['services']['creative']['environment']['MODRINTH_PROJECTS']
        lines = [l.strip() for l in projects.strip().split('\n')]
        # fabric-base group + modrinth_mods
        assert 'fabric-api' in lines
        assert 'lithium' in lines
        assert 'noisiumforked' in lines
        assert 'distanthorizons' in lines
        assert 'bluemap' in lines
        assert 'simple-voice-chat' in lines

    def test_modrinth_version_type(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        # creative has modrinth_version_type: beta (explicit)
        creative_env = compose['services']['creative']['environment']
        assert creative_env['MODRINTH_ALLOWED_VERSION_TYPE'] == 'beta'
        # test uses default (now beta), so key should also be present
        test_env = compose['services']['test']['environment']
        assert test_env['MODRINTH_ALLOWED_VERSION_TYPE'] == 'beta'

    def test_players(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        env = compose['services']['creative']['environment']
        assert env['OPS'] == 'd2683803'
        assert env['WHITELIST'] == 'd2683803,Kam93'

    def test_seed_quoted(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        test_env = compose['services']['test']['environment']
        assert test_env['SEED'] == '-4172144997902289642'
        # creative has no seed
        creative_env = compose['services']['creative']['environment']
        assert 'SEED' not in creative_env

    def test_seed_quoted_in_raw_yaml(self, sample_manifest):
        """Negative seeds must be quoted in YAML to avoid being parsed as numbers."""
        raw = mclib.generate_compose(sample_manifest)
        assert '"-4172144997902289642"' in raw

    def test_svc_port(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        creative_ports = compose['services']['creative']['ports']
        assert '24454:24454/udp' in creative_ports
        # test has svc: false
        test_ports = compose['services']['test']['ports']
        assert '24454:24454/udp' not in test_ports

    def test_bluemap_port(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        creative_ports = compose['services']['creative']['ports']
        assert '127.0.0.1:8100:8100' in creative_ports
        test_ports = compose['services']['test']['ports']
        assert '127.0.0.1:8101:8100' in test_ports

    def test_data_volume(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        assert './servers/creative/data:/data' in compose['services']['creative']['volumes']

    def test_resource_limits(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        creative_limits = compose['services']['creative']['deploy']['resources']['limits']
        assert creative_limits['memory'] == '5g'
        assert creative_limits['cpus'] == '2.0'  # permanent
        test_limits = compose['services']['test']['deploy']['resources']['limits']
        assert test_limits['memory'] == '3g'
        assert test_limits['cpus'] == '1.0'  # ephemeral

    def test_jar_mods_volume_and_env(self):
        """Servers with jar_mods get shared/mods volume and MODS env var."""
        manifest = {
            'players': {'ops': ['d2683803'], 'whitelist': ['d2683803']},
            'mod_groups': {},
            'servers': {
                'modded': {
                    'type': 'FABRIC',
                    'version': 'LATEST',
                    'mode': 'creative',
                    'memory': '2G',
                    'tier': 'ephemeral',
                    'mod_groups': [],
                    'modrinth_mods': [],
                    'jar_mods': ['custom-mod.jar', 'dev-build.jar'],
                    'svc': False,
                    'seed': None,
                    'motd': 'Modded Server',
                },
            },
        }
        compose = yaml.safe_load(mclib.generate_compose(manifest))
        modded = compose['services']['modded']
        assert './shared/mods:/shared-mods:ro' in modded['volumes']
        env = modded['environment']
        assert env['MODS'] == '/shared-mods/custom-mod.jar,/shared-mods/dev-build.jar'

    def test_no_ports_key_when_empty(self):
        """Server with no bluemap and no svc shouldn't have a ports key."""
        manifest = {
            'players': {'ops': ['d2683803'], 'whitelist': ['d2683803']},
            'mod_groups': {},
            'servers': {
                'vanilla': {
                    'type': 'VANILLA',
                    'version': 'LATEST',
                    'mode': 'survival',
                    'memory': '2G',
                    'tier': 'ephemeral',
                    'mod_groups': [],
                    'modrinth_mods': [],
                    'jar_mods': [],
                    'svc': False,
                    'bluemap': False,
                    'seed': None,
                    'motd': 'Vanilla Server',
                },
            },
        }
        compose = yaml.safe_load(mclib.generate_compose(manifest))
        assert 'ports' not in compose['services']['vanilla']

    def test_bluemap_autodetected_from_mods(self):
        """When bluemap field not set, infer from resolved mods."""
        manifest = {
            'players': {'ops': ['d2683803'], 'whitelist': ['d2683803']},
            'mod_groups': {},
            'servers': {
                'auto': {
                    'type': 'FABRIC',
                    'version': 'LATEST',
                    'mode': 'creative',
                    'memory': '2G',
                    'tier': 'ephemeral',
                    'mod_groups': [],
                    'modrinth_mods': ['bluemap'],
                    'jar_mods': [],
                    'svc': False,
                    'seed': None,
                    'motd': 'Auto Server',
                },
            },
        }
        compose = yaml.safe_load(mclib.generate_compose(manifest))
        ports = compose['services']['auto']['ports']
        # Should auto-detect bluemap and assign port
        assert any('8100' in str(p) for p in ports)


# ---------------------------------------------------------------------------
# Compose generation — pre-generation (Chunky)
# ---------------------------------------------------------------------------

class TestComposePregen:
    def _manifest_with_pregen(self, radius=5000):
        return {
            'players': {'ops': ['d2683803'], 'whitelist': ['d2683803']},
            'mod_groups': {'fabric-base': ['fabric-api', 'lithium']},
            'servers': {
                'survival': {
                    'type': 'FABRIC',
                    'version': 'LATEST',
                    'mode': 'survival',
                    'memory': '4G',
                    'tier': 'semi-permanent',
                    'mod_groups': ['fabric-base'],
                    'modrinth_mods': [],
                    'jar_mods': [],
                    'svc': False,
                    'seed': None,
                    'motd': 'Survival Server',
                    'pregen': {'radius': radius},
                },
            },
        }

    def test_chunky_added_to_modrinth_projects(self):
        manifest = self._manifest_with_pregen()
        compose = yaml.safe_load(mclib.generate_compose(manifest))
        projects = compose['services']['survival']['environment']['MODRINTH_PROJECTS']
        mods = [m.strip() for m in projects.strip().split('\n')]
        assert 'chunky' in mods

    def test_chunky_not_duplicated_if_already_present(self):
        manifest = self._manifest_with_pregen()
        manifest['servers']['survival']['modrinth_mods'] = ['chunky']
        compose = yaml.safe_load(mclib.generate_compose(manifest))
        projects = compose['services']['survival']['environment']['MODRINTH_PROJECTS']
        mods = [m.strip() for m in projects.strip().split('\n')]
        assert mods.count('chunky') == 1

    def test_rcon_cmds_startup(self):
        manifest = self._manifest_with_pregen(5000)
        compose = yaml.safe_load(mclib.generate_compose(manifest))
        env = compose['services']['survival']['environment']
        cmds = env['RCON_CMDS_STARTUP']
        assert 'chunky spawn' in cmds
        assert 'chunky radius 5000' in cmds

    def test_rcon_cmds_first_connect(self):
        manifest = self._manifest_with_pregen()
        compose = yaml.safe_load(mclib.generate_compose(manifest))
        env = compose['services']['survival']['environment']
        assert 'chunky start' in env['RCON_CMDS_FIRST_CONNECT']

    def test_rcon_cmds_last_disconnect(self):
        manifest = self._manifest_with_pregen()
        compose = yaml.safe_load(mclib.generate_compose(manifest))
        env = compose['services']['survival']['environment']
        assert 'chunky pause' in env['RCON_CMDS_LAST_DISCONNECT']

    def test_no_rcon_cmds_without_pregen(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        env = compose['services']['creative']['environment']
        assert 'RCON_CMDS_STARTUP' not in env
        assert 'RCON_CMDS_FIRST_CONNECT' not in env
        assert 'RCON_CMDS_LAST_DISCONNECT' not in env

    def test_custom_radius(self):
        manifest = self._manifest_with_pregen(1500)
        compose = yaml.safe_load(mclib.generate_compose(manifest))
        env = compose['services']['survival']['environment']
        assert 'chunky radius 1500' in env['RCON_CMDS_STARTUP']


# ---------------------------------------------------------------------------
# Compose generation — backup sidecars
# ---------------------------------------------------------------------------

class TestComposeBackupSidecars:
    def test_backup_sidecar_generated(self, sample_manifest):
        """creative has backup config, should get a sidecar."""
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        assert 'creative-backups' in compose['services']

    def test_no_sidecar_without_backup_config(self, sample_manifest):
        """test has no backup config, should not get a sidecar."""
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        assert 'test-backups' not in compose['services']

    def test_sidecar_image_and_network(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        sidecar = compose['services']['creative-backups']
        assert sidecar['image'] == 'itzg/mc-backup'
        assert 'minecraft-net' in sidecar['networks']
        assert sidecar['restart'] == 'unless-stopped'

    def test_sidecar_container_name(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        sidecar = compose['services']['creative-backups']
        assert sidecar['container_name'] == 'creative-backups'

    def test_sidecar_depends_on(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        sidecar = compose['services']['creative-backups']
        assert sidecar['depends_on'] == {
            'creative': {'condition': 'service_healthy'},
        }

    def test_sidecar_environment(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        env = compose['services']['creative-backups']['environment']
        assert env['RCON_HOST'] == 'creative'
        assert env['RCON_PASSWORD'] == '${RCON_PASSWORD:-changeme}'
        assert env['BACKUP_INTERVAL'] == '24h'
        assert env['INITIAL_DELAY'] == '2m'
        assert env['PRUNE_BACKUPS_COUNT'] == '3'

    def test_sidecar_volumes(self, sample_manifest):
        compose = yaml.safe_load(mclib.generate_compose(sample_manifest))
        volumes = compose['services']['creative-backups']['volumes']
        assert './servers/creative/data:/data:ro' in volumes
        assert './backups/creative:/backups' in volumes

    def test_custom_interval_and_keep(self):
        """Non-default backup settings from manifest."""
        manifest = {
            'players': {'ops': ['d2683803'], 'whitelist': ['d2683803']},
            'mod_groups': {},
            'servers': {
                'custom': {
                    'type': 'FABRIC',
                    'version': 'LATEST',
                    'mode': 'survival',
                    'memory': '4G',
                    'tier': 'permanent',
                    'mod_groups': [],
                    'modrinth_mods': [],
                    'jar_mods': [],
                    'svc': False,
                    'seed': None,
                    'motd': 'Custom Server',
                    'backup': {'interval': '6h', 'keep': 7},
                },
            },
        }
        compose = yaml.safe_load(mclib.generate_compose(manifest))
        env = compose['services']['custom-backups']['environment']
        assert env['BACKUP_INTERVAL'] == '6h'
        assert env['PRUNE_BACKUPS_COUNT'] == '7'

    def test_sidecar_ordered_after_server(self, sample_manifest):
        """Backup sidecar should appear after its server in the compose output."""
        raw = mclib.generate_compose(sample_manifest)
        server_pos = raw.index('creative:')
        sidecar_pos = raw.index('creative-backups:')
        assert server_pos < sidecar_pos


# ---------------------------------------------------------------------------
# Nginx generation
# ---------------------------------------------------------------------------

class TestNginxGeneration:
    def test_has_header_comment(self, sample_manifest):
        raw = mclib.generate_nginx(sample_manifest)
        assert raw.startswith('# Generated by mc-generate')

    def test_http_redirect(self, sample_manifest):
        raw = mclib.generate_nginx(sample_manifest)
        assert 'listen 80;' in raw
        assert 'return 301 https://$host$request_uri;' in raw

    def test_creative_server_block(self, sample_manifest):
        raw = mclib.generate_nginx(sample_manifest)
        assert 'server_name map-creative.mc.danny.is;' in raw
        assert 'proxy_pass http://127.0.0.1:8100;' in raw

    def test_test_server_block(self, sample_manifest):
        raw = mclib.generate_nginx(sample_manifest)
        assert 'server_name map-test.mc.danny.is;' in raw
        assert 'proxy_pass http://127.0.0.1:8101;' in raw

    def test_ssl_include(self, sample_manifest):
        raw = mclib.generate_nginx(sample_manifest)
        assert 'include /opt/minecraft/nginx/conf.d/ssl.conf;' in raw

    def test_websocket_support(self, sample_manifest):
        raw = mclib.generate_nginx(sample_manifest)
        assert 'proxy_set_header Upgrade $http_upgrade;' in raw
        assert 'proxy_set_header Connection "upgrade";' in raw

    def test_gzip_compression(self, sample_manifest):
        raw = mclib.generate_nginx(sample_manifest)
        assert 'gzip on;' in raw
        assert 'gzip_types' in raw
        assert 'application/javascript' in raw
        assert 'application/json' in raw

    def test_browser_caching(self, sample_manifest):
        raw = mclib.generate_nginx(sample_manifest)
        assert 'expires 1h;' in raw
        assert 'Cache-Control' in raw

    def test_no_block_for_non_bluemap_server(self):
        manifest = {
            'players': {'ops': [], 'whitelist': []},
            'mod_groups': {},
            'servers': {
                'vanilla': {
                    'type': 'VANILLA',
                    'mode': 'survival',
                    'memory': '2G',
                    'tier': 'ephemeral',
                    'bluemap': False,
                    'modrinth_mods': [],
                    'mod_groups': [],
                    'jar_mods': [],
                    'svc': False,
                },
            },
        }
        raw = mclib.generate_nginx(manifest)
        assert 'map-vanilla' not in raw

    def test_only_bluemap_servers_get_blocks(self):
        manifest = {
            'players': {'ops': [], 'whitelist': []},
            'mod_groups': {},
            'servers': {
                'mapped': {
                    'type': 'FABRIC',
                    'mode': 'creative',
                    'memory': '2G',
                    'tier': 'ephemeral',
                    'bluemap': True,
                    'bluemap_port': 8100,
                    'modrinth_mods': ['bluemap'],
                    'mod_groups': [],
                    'jar_mods': [],
                    'svc': False,
                },
                'unmapped': {
                    'type': 'VANILLA',
                    'mode': 'survival',
                    'memory': '2G',
                    'tier': 'ephemeral',
                    'bluemap': False,
                    'modrinth_mods': [],
                    'mod_groups': [],
                    'jar_mods': [],
                    'svc': False,
                },
            },
        }
        raw = mclib.generate_nginx(manifest)
        assert 'map-mapped.mc.danny.is' in raw
        assert 'map-unmapped' not in raw
